const lang = {
  en: {
    signIn: "Sign In",
    signUp: "Sign up",
    signOut: "Sign Out",
    name: "Name",
    email: "Email address",
    password: "Password",
    rememberMe: "Remember me",
    needHelp: "Need help?",
    newToNetflix: "New to Netflix? ",
    alreadyRegister: "Already register? ",
    signInNow: "Sign in now.",
    signUpNow: "Sign up now.",
    play: "Play",
    moreInfo: "More Info",
    nowPlaying: "Now Playing",
    topRated: "Top Rated",
    popular: "Popular",
    upcoming: "UpComing",
    tvSeries: "TV Series",
    gptSearch: "GPT Search",
    home: "Home",
    account: "Account",
    manageProfiles: "Manage Profiles",
    helpCentre: "Help Centre",
    watchToday: "What would you like to watch today?",
    search: "Search",
  },
  hi: {
    signIn: "साइन इन करें",
    signUp: "साइन अप करें",
    signOut: "साइन आउट",
    name: "नाम",
    email: "मेल पता",
    password: "पासवर्ड",
    rememberMe: "मुझे याद करो",
    needHelp: "मदद की ज़रूरत है?",
    newToNetflix: "नेटफ्लिक्स पर नए हैं? ",
    alreadyRegister: "पहले से ही पंजीकृत हैं? ",
    signInNow: "अब साइन इन करो।",
    signUpNow: "अभी साइनअप करें।",
    play: "चलाएं",
    moreInfo: "और जानकारी",
    nowPlaying: "अब चल रहा है",
    topRated: "शीर्ष रेटेड",
    popular: "लोकप्रिय",
    upcoming: "आगामी",
    tvSeries: "टीवी सीरीज़",
    gptSearch: "जीपीटी खोज",
    home: "घर",
    account: "खाता",
    manageProfiles: "प्रोफाइल प्रबंधित करें",
    helpCentre: "सहायता केंद्र",
    watchToday: "आज आप क्या देखना चाहेंगे?",
    search: "खोजें",
    nameMsg: "कृपया एक मान्य नाम दर्ज करें।",
    emailMsg: "कृपया एक मान्य ईमेल पता प्रविष्ट करें।",
    passMsg:
      "आपके पासवर्ड में कम से कम 8 अक्षर, बड़े अक्षर, छोटे अक्षर, संख्या और विशेष अक्षर होने चाहिए।",
  },
  bn: {},
};

export default lang;
